//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSB_SERVER.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSB_SERVER.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   START과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BUTTON_START {
            get {
                return ResourceManager.GetString("BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BUTTON_STOP {
            get {
                return ResourceManager.GetString("BUTTON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Mad Square&apos;s Brawl과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SERVER_GAME {
            get {
                return ResourceManager.GetString("SERVER_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MSB SERVER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SERVER_NAME {
            get {
                return ResourceManager.GetString("SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STATUS_DEFAULT {
            get {
                return ResourceManager.GetString("STATUS_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVER IS NOT RUNNING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STATUS_NOT_RUNNING {
            get {
                return ResourceManager.GetString("STATUS_NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STATUS_OFF {
            get {
                return ResourceManager.GetString("STATUS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STATUS_ON {
            get {
                return ResourceManager.GetString("STATUS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVER IS RUNNING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STATUS_RUNNING {
            get {
                return ResourceManager.GetString("STATUS_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVER IS STARTING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STATUS_STARTING {
            get {
                return ResourceManager.GetString("STATUS_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVER IS OFF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STATUS_STOPPED {
            get {
                return ResourceManager.GetString("STATUS_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVER HAS SUSPENDED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STATUS_SUSPENDED {
            get {
                return ResourceManager.GetString("STATUS_SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COMMAND과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_COMMAND {
            get {
                return ResourceManager.GetString("STRING_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEAM SQUARIAN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_COPYRIGHT {
            get {
                return ResourceManager.GetString("STRING_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROCESSOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_CPU {
            get {
                return ResourceManager.GetString("STRING_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DATABASE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_DATABASE {
            get {
                return ResourceManager.GetString("STRING_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ENVIRONMENT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_ENVIRONMENT {
            get {
                return ResourceManager.GetString("STRING_ENVIRONMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP or localhost과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_IP {
            get {
                return ResourceManager.GetString("STRING_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LIVE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_LIVE {
            get {
                return ResourceManager.GetString("STRING_LIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NETWORK LOG과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_LOG_NETWORK {
            get {
                return ResourceManager.GetString("STRING_LOG_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROOM LIST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_LOG_ROOM {
            get {
                return ResourceManager.GetString("STRING_LOG_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SYSTEM LOG과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_LOG_SYSTEM {
            get {
                return ResourceManager.GetString("STRING_LOG_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER LIST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_LOG_USER {
            get {
                return ResourceManager.GetString("STRING_LOG_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOGGER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_LOGGER {
            get {
                return ResourceManager.GetString("STRING_LOGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MODULE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_MODULE {
            get {
                return ResourceManager.GetString("STRING_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_PINGMODULE {
            get {
                return ResourceManager.GetString("STRING_PINGMODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_PORT {
            get {
                return ResourceManager.GetString("STRING_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MEMORY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_RAM {
            get {
                return ResourceManager.GetString("STRING_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROOM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_ROOM {
            get {
                return ResourceManager.GetString("STRING_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SOLO MM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_SOLOQUEUE {
            get {
                return ResourceManager.GetString("STRING_SOLOQUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to Start Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_START {
            get {
                return ResourceManager.GetString("STRING_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_STATUS {
            get {
                return ResourceManager.GetString("STRING_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to Stop Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_STOP {
            get {
                return ResourceManager.GetString("STRING_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEAM MM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_TEAMQUEUE {
            get {
                return ResourceManager.GetString("STRING_TEAMQUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPTIME과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_UPTIME {
            get {
                return ResourceManager.GetString("STRING_UPTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_USER {
            get {
                return ResourceManager.GetString("STRING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mad Square&apos;s Brawl Server v190821과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING_VERSION {
            get {
                return ResourceManager.GetString("STRING_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap title_end {
            get {
                object obj = ResourceManager.GetObject("title_end", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap title_max {
            get {
                object obj = ResourceManager.GetObject("title_max", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap title_min {
            get {
                object obj = ResourceManager.GetObject("title_min", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
