//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSB_SERVER.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSB_SERVER.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string BUTTON_START {
            get {
                return ResourceManager.GetString("BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        public static string BUTTON_STOP {
            get {
                return ResourceManager.GetString("BUTTON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mad Square&apos;s Brawl.
        /// </summary>
        public static string SERVER_GAME {
            get {
                return ResourceManager.GetString("SERVER_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB SERVER.
        /// </summary>
        public static string SERVER_NAME {
            get {
                return ResourceManager.GetString("SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string STATUS_DEFAULT {
            get {
                return ResourceManager.GetString("STATUS_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER IS NOT RUNNING.
        /// </summary>
        public static string STATUS_NOT_RUNNING {
            get {
                return ResourceManager.GetString("STATUS_NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string STATUS_OFF {
            get {
                return ResourceManager.GetString("STATUS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string STATUS_ON {
            get {
                return ResourceManager.GetString("STATUS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER IS RUNNING.
        /// </summary>
        public static string STATUS_RUNNING {
            get {
                return ResourceManager.GetString("STATUS_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER IS STARTING.
        /// </summary>
        public static string STATUS_STARTING {
            get {
                return ResourceManager.GetString("STATUS_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER IS OFF.
        /// </summary>
        public static string STATUS_STOPPED {
            get {
                return ResourceManager.GetString("STATUS_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER HAS SUSPENDED.
        /// </summary>
        public static string STATUS_SUSPENDED {
            get {
                return ResourceManager.GetString("STATUS_SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMAND.
        /// </summary>
        public static string STRING_COMMAND {
            get {
                return ResourceManager.GetString("STRING_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM SQUARIAN.
        /// </summary>
        public static string STRING_COPYRIGHT {
            get {
                return ResourceManager.GetString("STRING_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSOR.
        /// </summary>
        public static string STRING_CPU {
            get {
                return ResourceManager.GetString("STRING_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE.
        /// </summary>
        public static string STRING_DATABASE {
            get {
                return ResourceManager.GetString("STRING_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVIRONMENT.
        /// </summary>
        public static string STRING_ENVIRONMENT {
            get {
                return ResourceManager.GetString("STRING_ENVIRONMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP or localhost.
        /// </summary>
        public static string STRING_IP {
            get {
                return ResourceManager.GetString("STRING_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE.
        /// </summary>
        public static string STRING_LIVE {
            get {
                return ResourceManager.GetString("STRING_LIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETWORK LOG.
        /// </summary>
        public static string STRING_LOG_NETWORK {
            get {
                return ResourceManager.GetString("STRING_LOG_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROOM LIST.
        /// </summary>
        public static string STRING_LOG_ROOM {
            get {
                return ResourceManager.GetString("STRING_LOG_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM LOG.
        /// </summary>
        public static string STRING_LOG_SYSTEM {
            get {
                return ResourceManager.GetString("STRING_LOG_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER LIST.
        /// </summary>
        public static string STRING_LOG_USER {
            get {
                return ResourceManager.GetString("STRING_LOG_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGGER.
        /// </summary>
        public static string STRING_LOGGER {
            get {
                return ResourceManager.GetString("STRING_LOGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODULE.
        /// </summary>
        public static string STRING_MODULE {
            get {
                return ResourceManager.GetString("STRING_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PING.
        /// </summary>
        public static string STRING_PINGMODULE {
            get {
                return ResourceManager.GetString("STRING_PINGMODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORT.
        /// </summary>
        public static string STRING_PORT {
            get {
                return ResourceManager.GetString("STRING_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMORY.
        /// </summary>
        public static string STRING_RAM {
            get {
                return ResourceManager.GetString("STRING_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROOM.
        /// </summary>
        public static string STRING_ROOM {
            get {
                return ResourceManager.GetString("STRING_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLO MM.
        /// </summary>
        public static string STRING_SOLOQUEUE {
            get {
                return ResourceManager.GetString("STRING_SOLOQUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Start Server.
        /// </summary>
        public static string STRING_START {
            get {
                return ResourceManager.GetString("STRING_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string STRING_STATUS {
            get {
                return ResourceManager.GetString("STRING_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Stop Server.
        /// </summary>
        public static string STRING_STOP {
            get {
                return ResourceManager.GetString("STRING_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM MM.
        /// </summary>
        public static string STRING_TEAMQUEUE {
            get {
                return ResourceManager.GetString("STRING_TEAMQUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPTIME.
        /// </summary>
        public static string STRING_UPTIME {
            get {
                return ResourceManager.GetString("STRING_UPTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        public static string STRING_USER {
            get {
                return ResourceManager.GetString("STRING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mad Square&apos;s Brawl Server v200412A.
        /// </summary>
        public static string STRING_VERSION {
            get {
                return ResourceManager.GetString("STRING_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap title_end {
            get {
                object obj = ResourceManager.GetObject("title_end", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap title_max {
            get {
                object obj = ResourceManager.GetObject("title_max", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap title_min {
            get {
                object obj = ResourceManager.GetObject("title_min", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
